version: "2"
services:
  otel-agent:
    image: otel/opentelemetry-collector:0.37.0
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=debug"]
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "6832:6832/udp" # Jaeger receiver
  price:
    image: us.gcr.io/galoy-org/price:edge
    ports:
    - "50051:50051"
    - "9464:9464"
  redis:
    image: bitnami/redis:6.2
    ports:
    - "6379:6379"
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  mongodb:
    image: bitnami/mongodb:4.4.6-debian-10-r0
    ports:
    - "27017:27017"
    environment:
    - MONGODB_PASSWORD=password
    - MONGODB_USERNAME=testGaloy
    - MONGODB_DATABASE=galoy
    - MONGODB_REPLICA_SET_MODE=primary
    - MONGODB_ROOT_PASSWORD=password
    - MONGODB_REPLICA_SET_KEY=replicasetkey
    - MONGODB_ADVERTISED_HOSTNAME=${DOCKER_HOST_IP:-127.0.0.1}
  bitcoind:
    image: lncm/bitcoind:v0.21.1
    ports:
      - "18443:18443"
    volumes:
    - ${PWD}/dev/bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
  lnd1:
    image: lncm/lnd:v0.13.3-monitoring
    ports:
      - "10009:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/data/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/data/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/data/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd2:
    image: lncm/lnd:v0.13.3-monitoring
    ports:
      - "10010:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/data/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/data/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/data/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd-outside-1:
    image: lncm/lnd:v0.13.3-monitoring
    ports:
      - "10012:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/data/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/data/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/data/.lnd/tls.cert
    depends_on: [bitcoind]
  lnd-outside-2:
    image: lncm/lnd:v0.13.3-monitoring
    ports:
      - "10013:10009"
    volumes:
    - ${PWD}/dev/lnd/lnd.conf:/data/.lnd/lnd.conf
    - ${PWD}/dev/lnd/tls.key:/data/.lnd/tls.key
    - ${PWD}/dev/lnd/tls.cert:/data/.lnd/tls.cert
    depends_on: [bitcoind]
