receivers:
  jaeger:
    protocols:
      thrift_compact: # on port 6831
      thrift_binary: # on port 6832

processors:
  batch:

exporters:
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [logging]

