version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  # gcp-gke: circleci/gcp-gke@1.1.0
  # helm: circleci/helm@1.2.0
  gcp-gcr: circleci/gcp-gcr@0.7.1
  slack: circleci/slack@3.4.2


commands:
  gke-auth:
    steps:
      - run:
          name: Authenticate on gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} > gcloud-service-key.json
            gcloud auth activate-service-account --key-file=gcloud-service-key.json
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud container clusters get-credentials testnet-cluster --region us-central1-a --project ${GOOGLE_PROJECT_ID}

jobs:
  build_test_image:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Write build params to docker image source
          command: |
            echo "COMMITHASH=$CIRCLE_SHA1" >> ./.env
            echo "BUILDTIME=$(date -u '+%F-%T')" >> ./.env
      - gcp-gcr/build-image:
          image: galoy
          tag: $CIRCLE_SHA1
      - gcp-gcr/build-image:
          image: galoy
          dockerfile: Dockerfile-debug
          tag: $CIRCLE_SHA1-debug
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: galoy
          tag: $CIRCLE_SHA1
      - gcp-gcr/push-image:
          image: galoy
          tag: $CIRCLE_SHA1-debug

  test:
    docker:
      - image: kiwigrid/gcloud-kubectl-helm:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: generate and export namespace name
          command: |
            echo "export NAMESPACE=devnet-$CIRCLE_SHA1" >> $BASH_ENV
      - gke-auth
      - run:
          name: create namespace
          command: |
            kubectl create namespace $NAMESPACE
      - run:
          name: install helm charts
          command: ./initLocalTest.sh
      - run:
          name: Run jest test
          command: |
            kubectl exec --namespace=$NAMESPACE $(kubectl get pods --namespace=$NAMESPACE --selector=app=testpod --output=jsonpath={.items..metadata.name}) -- /nodejs/bin/node node_modules/.bin/jest --ci --reporters=default --reporters=jest-junit --forceExit
            # export JEST_JUNIT_OUTPUT_DIR=\"./artifacts\" && jest --ci --reporters=default --reporters=jest-junit --forceExit
            
            # kubectl run --generator=run-pod/v1 --image=gcr.io/galoyapp/galoy:$CIRCLE_SHA1-debug test -it -- ./node_modules/.bin/jest
            # kubectl exec --namespace=$NAMESPACE $(kubectl get pods --namespace=$NAMESPACE --selector=app=testpod --output=jsonpath={.items..metadata.name}) -- sh -c "yarn test --max_old_space_size=3000"
            # kubectl run --image=gcr.io/galoyapp/galoy:$CIRCLE_SHA1 test -it --overrides='{"spec":{"containers[0]":[{"env":[{"name":"MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"name":"galoy-mongodb","key":"mongodb-password"}}},{"name":"MONGODB_USER","value":"testGaloy"},{"name":"MONGODB_ADDRESS","value":"galoy-mongodb-headless"},{"name":"LNDIP","value":"lnd"},{"name":"MACAROON","valueFrom":{"secretKeyRef":{"name":"lnd-macaroon","key":"admin.macaroon"}}},{"name":"TLS","valueFrom":{"secretKeyRef":{"name":"lnd-tls","key":"tls.cert"}}},{"name":"BITCOINDADDR","value":"bitcoind"},{"name":"BITCOINDPORT","value":"18443"},{"name":"JWT_SECRET","value":"my-secret"},{"name":"NETWORK","valueFrom":{"secretKeyRef":{"name":"network","key":"network"}}},{"name":"REDIS_PORT","value":"6379"},{"name":"REDIS_IP","value":"galoy-redis-master"},{"name":"MACAROONOUTSIDE1","valueFrom":{"secretKeyRef":{"name":"lnd-outside-1-macaroon","key":"admin.macaroon"}}},{"name":"TLSOUTSIDE1","valueFrom":{"secretKeyRef":{"name":"lnd-outside-1-tls","key":"tls.cert"}}},{"name":"MACAROONOUTSIDE2","valueFrom":{"secretKeyRef":{"name":"lnd-outside-2-macaroon","key":"admin.macaroon"}}},{"name":"TLSOUTSIDE2","valueFrom":{"secretKeyRef":{"name":"lnd-outside-2-tls","key":"tls.cert"}}},{"name":"LNDRPCPORT","value":"10009"},{"name":"LNDOUTSIDE1RPCPORT","value":"10009"},{"name":"LNDOUTSIDE2RPCPORT","value":"10009"},{"name":"LNDOUTSIDE1ADDR","value":"lnd-outside-1"},{"name":"LNDOUTSIDE2ADDR","value":"lnd-outside-2"}]}]}}' -- ./node_modules/.bin/jest
            # kubectl run -it --restart=Never --image=notused --overrides='{"spec":{"containers":[{"name":"graphql","image":"gcr.io/galoyapp/galoy:391b62193b3707ce86c33c2ea3a3c79e1d347677","args":["./node_modules/.bin/jest"],"volumeMounts":[{"name":"custom-yaml","mountPath":"/var/yaml/"}],"ports":[{"name":"http","containerPort":4000,"protocol":"TCP"}],"resources":{"requests":{"cpu":"100m"},"limits":{"cpu":"1000m"}},"env":[{"name":"HELMREVISION","value":"1"},{"name":"MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"name":"galoy-mongodb","key":"mongodb-password"}}},{"name":"MONGODB_USER","value":"testGaloy"},{"name":"MONGODB_ADDRESS","value":"galoy-mongodb"},{"name":"LNDIP","value":"lnd"},{"name":"MACAROON","valueFrom":{"secretKeyRef":{"name":"lnd-macaroon","key":"admin.macaroon"}}},{"name":"TLS","valueFrom":{"secretKeyRef":{"name":"lnd-tls","key":"tls.cert"}}},{"name":"BITCOINDADDR","value":"bitcoind"},{"name":"BITCOINDPORT","value":"18443"},{"name":"JWT_SECRET","value":"my_secret"},{"name":"NETWORK","valueFrom":{"secretKeyRef":{"name":"network","key":"network"}}},{"name":"REDIS_PORT","value":"6379"},{"name":"REDIS_IP","value":"galoy-redis-master"},{"name":"LOGLEVEL","value":"debug"},{"name":"MACAROONOUTSIDE1","valueFrom":{"secretKeyRef":{"name":"lnd-outside-1-macaroon","key":"admin.macaroon"}}},{"name":"TLSOUTSIDE1","valueFrom":{"secretKeyRef":{"name":"lnd-outside-1-tls","key":"tls.cert"}}},{"name":"MACAROONOUTSIDE2","valueFrom":{"secretKeyRef":{"name":"lnd-outside-2-macaroon","key":"admin.macaroon"}}},{"name":"TLSOUTSIDE2","valueFrom":{"secretKeyRef":{"name":"lnd-outside-2-tls","key":"tls.cert"}}},{"name":"LNDRPCPORT","value":"10009"},{"name":"LNDOUTSIDE1RPCPORT","value":"10009"},{"name":"LNDOUTSIDE2RPCPORT","value":"10009"},{"name":"LNDOUTSIDE1ADDR","value":"lnd-outside-1"},{"name":"LNDOUTSIDE2ADDR","value":"lnd-outside-2"}]}],"volumes":[{"name":"custom-yaml","secret":{"secretName":"galoy-config-map"}}]}}' test
      - run:
          name: Run postman test
          command: |
            kubectl exec --namespace=$NAMESPACE $(kubectl get pods --namespace=$NAMESPACE --selector=app=testpod --output=jsonpath={.items..metadata.name}) -- sh -c "yarn run postman"
      # - run:
      #     name: sleep
      #     command: sleep 590 && echo "10 min" && sleep 590 && echo "20 min" && sleep 590 && echo "30 min"
      #     when: always
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
      - run:
          name: Delete devnet namespace
          command: |
            kubectl delete namespaces $NAMESPACE
          when: always

  testnet_deploy:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - gcp-cli/install
      - gke-auth
      - run: curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
      - run: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
      - run: echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
      - run: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      - run: sudo apt-get update
      - run: sudo apt-get install -y kubectl helm
      - run:
          name: Upgrade testnet deployments
          command: ./initLocalTest.sh testnet

  mainnet_deploy:
    docker:
      - image: kiwigrid/gcloud-kubectl-helm:latest
    resource_class: small
    steps:
      - checkout
      - gke-auth
      - run:
          name: Upgrade mainnet deployments
          command: |
            ./initLocalTest.sh mainnet

workflows:
  kube:
    jobs:
      - build_test_image
      - test:
          requires:
            - build_test_image
      - testnet_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - approve_mainnet_deploy:
          type: approval
          requires:
            - testnet_deploy
          filters:
            branches:
              only:
                - main
      - slack/approval-notification:
          mentions: 'U011J7RCEFQ,U011KKL1L4B'
          requires:
            - testnet_deploy
          filters:
            branches:
              only:
                - main
      - mainnet_deploy:
          requires:
            - approve_mainnet_deploy
          filters:
            branches:
              only:
                - main
