{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.deployment.name}}
  name: {{ printf "%s-lnpage" .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
    spec:
      containers:
      - image: "{{.Values.image.name}}:{{.Values.image.tag}}"
        name: {{.Values.deployment.name}}-container
        ports:
          - name: http
            containerPort: 80
{{- end }}
