apiVersion: v1
kind: ConfigMap
metadata:
  name: galoy-config-map
  labels:
    app: galoy
    app.kubernetes.io/managed-by: Helm
data:
  custom.yaml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.galoy "context" $) | nindent 4 }}
