{{- range .Values.cron }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            {{- if .command }}
            command: ["/bin/sh","-c", {{ .command | quote }}]
            {{- end }}
            {{- if .args }}
            args: {{ .args }}
            {{- end }}
            volumeMounts:
            - name: firebase-serviceaccount
              mountPath: "/tmp/firebase-serviceaccount"
              readOnly: true
            - name: "custom-yaml"
              mountPath: "/var/yaml/"
            env:
            - name: NETWORK
              valueFrom:
                secretKeyRef:
                  name: network
                  key: network
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-mongodb
                  key: "mongodb-password"
            - name: MONGODB_USER
              value: "testGaloy"
            - name: MONGODB_ADDRESS
              value: {{ $.Values.mongodbaddress }}
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DB
              value: "galoy"
            - name: LNDDNS
              value: "lnd"
            - name: MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd-credentials
                  key: admin_macaroon_base64
            - name: TLS
              valueFrom:
                secretKeyRef:
                  name: lnd-credentials
                  key: tls_base64
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "galoy-redis-master"
            - name: BITCOINDADDR
              value: "bitcoind"
            - name: BITCOINDRPCPASS
              valueFrom:
                secretKeyRef:
                  name: bitcoind-rpcpassword
                  key: password
            - name: BITCOINDPORT
              value: {{ $.Values.bitcoind.port | quote }}
            - name: LOGLEVEL
              value: debug
            - name: FTX_KEY
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: key
            - name: FTX_SECRET
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: secret
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/firebase-serviceaccount/galoyapp-firebase-serviceaccont.json"
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dropbox-access-token
                  key: token
          restartPolicy: OnFailure
          volumes:
          - name: firebase-serviceaccount
            secret:
              secretName: galoyapp-firebase-serviceaccount
          - name: "custom-yaml"
            secret:
              secretName: "galoy-config-map"
      
---
{{- end }}
