{{- range $.Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/managed-by: Helm
    kube-monkey/enabled: enabled
    kube-monkey/identifier: {{.name}}
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "8"
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      name: {{ .name }}
      labels:
        app: {{ .name }}
        kube-monkey/enabled: enabled
        kube-monkey/identifier: {{.name}}
    {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}{{- if .debugContainer -}}-debug{{- end -}}"
          {{- if .command }}
          command: ["/bin/sh","-c", {{ .command }}]
          {{- end }}
          {{- if .args }}
          args: {{ .args }}
          {{- end }}
          volumeMounts:
          {{- if $.Values.needFirebaseServiceAccount }}
          - name: firebase-serviceaccount
            mountPath: "/tmp/firebase-serviceaccount"
            readOnly: true
          {{- end}}
          {{- if eq .name "trigger" }}
          - name: "service-account"
            mountPath: "/var/secret/cloud.google.com"
          {{- end}}
          - name: "custom-yaml"
            mountPath: "/var/yaml/"
          {{- if .targetPort }}
          ports:
            - name: http
              containerPort: {{ .targetPort }}
              protocol: TCP
          {{- end }}
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          env:
            - name: HELMREVISION
              value: {{ $.Release.Revision | quote}}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-mongodb
                  key: "mongodb-password"
            - name: MONGODB_USER
              value: "testGaloy"
            - name: MONGODB_ADDRESS
              value: {{ $.Values.mongodbaddress }}

            - name: LND_1_DNS
              value: "lnd"
            - name: LND_1_MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd-macaroon
                  key: admin.macaroon
            - name: LND_1_TLS
              valueFrom:
                secretKeyRef:
                  name: lnd-tls
                  key: tls.cert
                  
            - name: BITCOINDADDR
              value: "bitcoind"
            - name: BITCOINDPORT
              value: {{ $.Values.bitcoind.port | quote }}
            - name: JWT_SECRET
            {{- if $.Values.jwtSecret}}
              value: {{ $.Values.jwtSecret }}
            {{- else}}
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            {{- end}}
            - name: NETWORK
              valueFrom:
                secretKeyRef:
                  name: network
                  key: network
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_IP
              value: "galoy-redis-master"
            {{- if eq .name "exporter" }}
            - name: FTX_KEY
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: key
            - name: FTX_SECRET
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: secret
            {{- end}}
            {{- if $.Values.loglevel}}
            - name: LOGLEVEL
              value: {{ $.Values.loglevel }}
            {{- end}}
            {{- if $.Values.needFirebaseServiceAccount }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/firebase-serviceaccount/galoyapp-firebase-serviceaccont.json"
            {{- end }}
            {{- if eq .name "trigger" }}
            - name: "GCS_APPLICATION_CREDENTIALS"
              value: "/var/secret/cloud.google.com/galoyapp-31518a00082f.json"
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dropbox-access-token
                  key: token
            {{- end }}
            {{- if eq $.Values.global.network "regtest" }}
            - name: MACAROONOUTSIDE1
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-1-macaroon
                  key: admin.macaroon
            - name: TLSOUTSIDE1
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-1-tls
                  key: tls.cert
            - name: MACAROONOUTSIDE2
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-2-macaroon
                  key: admin.macaroon
            - name: TLSOUTSIDE2
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-2-tls
                  key: tls.cert
            - name: LNDOUTSIDE1ADDR
              value: "lnd-outside-1"
            - name: LNDOUTSIDE2ADDR
              value: "lnd-outside-2"
            {{- else }}
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_PHONE_NUMBER
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_API_KEY
            - name: TWILIO_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_API_SECRET
            {{- end }}
          {{- if .healthz }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .targetPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .targetPort }}
            initialDelaySeconds: 5
            failureThreshold: 5
            successThreshold: 2
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          {{- end }}
      volumes:
      {{- if $.Values.needFirebaseServiceAccount }}
      - name: firebase-serviceaccount
        secret:
          secretName: galoyapp-firebase-serviceaccount
      {{- end}}
      {{- if eq .name "trigger" }}
      - name: "service-account"
        secret:
          secretName: "gcs-sa-key"
      {{- end}}
      - name: "custom-yaml"
        secret:
          secretName: "galoy-config-map"
---
{{- end }}
