{{ if .Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app: {{ .Values.ingress.name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/limit-rpm: "12"
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /swagger {
          deny all;

          proxy_http_version 1.1;
          proxy_redirect off;
          proxy_intercept_errors on;
          proxy_set_header Connection "";
          proxy_set_header X-CF-Visitor $http_cf_visitor;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://devns-quests-ingress-dev.example.com-some-service;
      }
spec:
  tls:
  - hosts:
    - {{.Values.ingress.host}}
    secretName: {{.Values.network}}-tls
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: /swagger
        backend:
          serviceName: graphql
          servicePort: 4000
      - path: /
        backend:
          serviceName: graphql
          servicePort: 4000
{{ end }}