#@ load("@ytt:data", "data")

#@ galoy_image_digest = "sha256@d0fb913ae1129496fc1b7aacaf90f274bf94be6ee994a78ad304aec0e5fc23f1"
#@ mongodb_migrate_image_digest = "sha256@d19080325fee24e6e7d0e3c21c513af8a05e92326c69d202ed6ad602004ff80c"

version: #@ data.values.version
services:
  quickstart-test:
    image: busybox
    depends_on:
      - apollo-router
      - oathkeeper
      - kratos
      - kratos-pg
      - galoy
      - trigger
      - redis
      - mongodb
      - mongodb-migrate
      - price
      - bitcoind
      - bitcoind-signer
      - lnd1
      - lnd-outside-1
      - postgres-bria
      - fulcrum
      - stablesats
      - svix
      - svix-pg
    restart: on-failure:10

  #! Proxies
  apollo-router: #@ data.values.services["apollo-router"]
  oathkeeper: #@ data.values.services["oathkeeper"]

  #! Authentication
  kratos: #@ data.values.services["kratos"]
  kratos-pg: #@ data.values.services["kratos-pg"]

  galoy:
#@ if galoy_image_digest == "local":
    build:
      context: ../
#@ elif galoy_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-app@" + galoy_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-app:" + galoy_image_digest
#@ end
    command:
      - "-r"
      - "/app/lib/services/tracing.js"
      - "lib/servers/graphql-main-server.js"
    env_file: ${HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}/.env.galoy
    depends_on:
    - trigger
    - apollo-router
    - oathkeeper
    - kratos
    - lnd1
    - lnd-outside-1
    - bria
    - mongodb
    - redis
    - stablesats
    networks:
      default:
        aliases:
        - bats-tests
  trigger:
#@ if galoy_image_digest == "local":
    build:
      context: ../
#@ elif galoy_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-app@" + galoy_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-app:" + galoy_image_digest
#@ end
    command:
      - "-r"
      - "/app/lib/services/tracing.js"
      - "lib/servers/trigger.js"
    env_file: ${HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}/.env.galoy
    depends_on:
    - lnd1
    - bria
    - mongodb

  #! Database
  redis: #@ data.values.services["redis"]
  mongodb: #@ data.values.services["mongodb"]
  mongodb-migrate:
#@ if mongodb_migrate_image_digest == "local":
    build:
      context: ../
      dockerfile: Dockerfile-migrate
#@ elif mongodb_migrate_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-app-migrate@" + mongodb_migrate_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-app-migrate:" + mongodb_migrate_image_digest
#@ end
    depends_on:
    - mongodb
    environment:
    - MONGODB_ADDRESS=mongodb

  #! Price
  price: #@ data.values.services["price"]
  price-history: #@ data.values.services["price-history"]
  price-history-migrate: #@ data.values.services["price-history-migrate"]
  postgres-price-history: #@ data.values.services["postgres-price-history"]

  #! Bitcoin stack
  bitcoind: #@ data.values.services["bitcoind"]
  bitcoind-signer: #@ data.values.services["bitcoind-signer"]
  lnd1: #@ data.values.services["lnd1"]
  lnd-outside-1: #@ data.values.services["lnd-outside-1"]
  bria: #@ data.values.services["bria"]
  postgres-bria: #@ data.values.services["postgres-bria"]
  fulcrum: #@ data.values.services["fulcrum"]

  #! Stablesats
  stablesats: #@ data.values.services["stablesats"]

  #! Otel
  otel-agent: #@ data.values.services["otel-agent"]

  #! Svix / callbacks
  svix: #@ data.values.services["svix"]
  svix-pg: #@ data.values.services["svix-pg"]

#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
services:
  #@overlay/match by=overlay.all, expects="1+"
  _:
    #@overlay/match when=1
    #@overlay/remove
    extra_hosts: _
    #@overlay/match when=1
    volumes:
    #@overlay/match by=overlay.all, expects="0+"
    #@overlay/replace via=lambda left, right: left.replace("HOST_PROJECT_PATH:-.}", "HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}")
    - REPLACED
