#@ load("@ytt:data", "data")

#@ galoy_api_image_digest = "sha256@c23bd49cf351c9c43ea9e53ed0dbfb66214ab33d13e1a00bd4f8c0a7fd10a0a9"
#@ galoy_trigger_image_digest = "sha256@82f5531ae7e86a94e9792c2608ac3366bc3b3c62fb77f1dae6fcab3fa487eeaf"
#@ mongodb_migrate_image_digest = "sha256@2fde3d48c9f92471a1afcb842cd738440de6e1c6b9e539df4dfbabdc3418fa25"

version: #@ data.values.version
services:
  quickstart-test:
    image: busybox
    depends_on:
      - apollo-router
      - oathkeeper
      - kratos
      - kratos-pg
      - galoy
      - trigger
      - redis
      - mongodb
      - mongodb-migrate
      - price
      - bitcoind
      - bitcoind-signer
      - lnd1
      - lnd-outside-1
      - postgres-bria
      - fulcrum
      - stablesats
      - svix
      - svix-pg
      - hydra
    restart: on-failure:10

  #! Proxies
  apollo-router: #@ data.values.services["apollo-router"]
  oathkeeper: #@ data.values.services["oathkeeper"]

  #! Authentication
  kratos: #@ data.values.services["kratos"]
  kratos-pg: #@ data.values.services["kratos-pg"]

  hydra: #@ data.values.services["hydra"]
  hydra-migrate: #@ data.values.services["hydra-migrate"]
  postgresdhydra: #@ data.values.services["postgresdhydra"]

  galoy:
#@ if galoy_api_image_digest == "local":
    build:
      context: ..
      dockerfile: core/api/Dockerfile
#@ elif galoy_api_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-api@" + galoy_api_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-api:" + galoy_api_image_digest
#@ end
    env_file: ${HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}/.env.galoy
    depends_on:
    - trigger
    - apollo-router
    - oathkeeper
    - kratos
    - lnd1
    - lnd-outside-1
    - bria
    - mongodb
    - redis
    - stablesats
    networks:
      default:
        aliases:
        - bats-tests
  trigger:
#@ if galoy_trigger_image_digest == "local":
    build:
      context: ..
      dockerfile: core/api-trigger/Dockerfile
#@ elif galoy_trigger_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-api-trigger@" + galoy_trigger_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-api-trigger:" + galoy_trigger_image_digest
#@ end
    env_file: ${HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}/.env.galoy
    depends_on:
    - lnd1
    - bria
    - mongodb

  #! Database
  redis: #@ data.values.services["redis"]
  mongodb: #@ data.values.services["mongodb"]
  mongodb-migrate:
#@ if mongodb_migrate_image_digest == "local":
    build:
      context: ..
      dockerfile: core/api/Dockerfile-migrate
#@ elif mongodb_migrate_image_digest.startswith("sha256@"):
    image: #@ "us.gcr.io/galoy-org/galoy-app-migrate@" + mongodb_migrate_image_digest.replace("@",":")
#@ else:
    image: #@ "us.gcr.io/galoy-org/galoy-app-migrate:" + mongodb_migrate_image_digest
#@ end
    depends_on:
    - mongodb
    environment:
    - MONGODB_ADDRESS=mongodb

  #! Price
  price: #@ data.values.services["price"]
  price-history: #@ data.values.services["price-history"]
  price-history-migrate: #@ data.values.services["price-history-migrate"]
  postgres-price-history: #@ data.values.services["postgres-price-history"]

  #! Bitcoin stack
  bitcoind: #@ data.values.services["bitcoind"]
  bitcoind-signer: #@ data.values.services["bitcoind-signer"]
  lnd1: #@ data.values.services["lnd1"]
  lnd-outside-1: #@ data.values.services["lnd-outside-1"]
  bria: #@ data.values.services["bria"]
  postgres-bria: #@ data.values.services["postgres-bria"]
  fulcrum: #@ data.values.services["fulcrum"]

  #! Stablesats
  stablesats: #@ data.values.services["stablesats"]

  #! Otel
  otel-agent: #@ data.values.services["otel-agent"]

  #! Svix / callbacks
  svix: #@ data.values.services["svix"]
  svix-pg: #@ data.values.services["svix-pg"]

#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.all
---
services:
  #@overlay/match by=overlay.all, expects="1+"
  _:
    #@overlay/match when=1
    #@overlay/remove
    extra_hosts: _
    #@overlay/match when=1
    volumes:
    #@overlay/match by=overlay.all, expects="0+"
    #@overlay/replace via=lambda left, right: str(left).replace("HOST_PROJECT_PATH:-.}", "HOST_PROJECT_PATH:-.}/${GALOY_QUICKSTART_PATH:-vendor/galoy-quickstart}")
    - REPLACED

#@overlay/match by=overlay.all
---
services:
  svix:
    #@overlay/match missing_ok=True
    extra_hosts:
      - "dockerhost-alias:host-gateway"
