apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 33d36e0c223aa108c633e5abbfa0f673c15d7bdf
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./graphql
  contents:
  - path: schemas/
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 33d36e0c223aa108c633e5abbfa0f673c15d7bdf
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
  - path: gql/
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 33d36e0c223aa108c633e5abbfa0f673c15d7bdf
    includePaths:
    - bats/gql/**/*
    newRootPath: bats/gql
