apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: f02263e79f119602d6e63a8d9c2ca8914e3a8c08
    includePaths:
    - core/api/dev/**/*
    excludePaths:
    - core/api/dev/bin/**/*
    - core/api/dev/.gitignore
    newRootPath: core/api/dev
- path: ./galoy
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: f02263e79f119602d6e63a8d9c2ca8914e3a8c08
    includePaths:
    - core/api/dev/**/*
    - core/api/test/bats/bitcoind_signer_descriptors.json
    - core/api/test/bats/gql/*
    - core/api/.env
    - core/api/.envrc
    - core/api/.env.ci
    - core/api/docker-compose.yml
    - core/api/docker-compose.override.yml
    excludePaths:
    - core/api/dev/bin/**/*
    newRootPath: core/api
- path: ./graphql
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: f02263e79f119602d6e63a8d9c2ca8914e3a8c08
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
