apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: e399836a19dd16465f714e9a142760c8852602f8
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./galoy
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: e399836a19dd16465f714e9a142760c8852602f8
    includePaths:
    - dev/**/*
    - test/bats/bitcoind_signer_descriptors.json
    - test/bats/gql/*
    - .envrc
    - .env.ci
    - docker-compose.yml
    - docker-compose.override.yml
    excludePaths:
    - dev/bin/**/*
- path: ./graphql
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: e399836a19dd16465f714e9a142760c8852602f8
    includePaths:
    - src/graphql/public/schema.graphql
    - src/graphql/admin/schema.graphql
    newRootPath: src/graphql
