apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 05ae7d9fec7701175d65ad7f221092846b2be201
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./graphql
  contents:
  - path: schemas/
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 05ae7d9fec7701175d65ad7f221092846b2be201
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
  - path: gql/
    git:
      url: https://github.com/GaloyMoney/galoy.git
      ref: 05ae7d9fec7701175d65ad7f221092846b2be201
    includePaths:
    - bats/gql/**/*
    newRootPath: bats/gql
